version: '3.7'

services:
  sample:
    container_name: sample
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3030:3030'
    volumes:
      - .:/app
    command: npm start
